apiVersion: apps/v1 
kind: Deployment
metadata:
  name: predict-imdb 
  labels:
    app: imdb-server
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: imdb-server
  template:
    metadata:
      labels:
        app: imdb-server
    spec:
      containers:
      - name: app
        image: canhnt/imdb_keras:latest
        imagePullPolicy: Always
        command: ["/bin/sh", "-c"]
        args:
         - python server.py;
        ports:
        - containerPort: 8080
          protocol: TCP
